PyCQA/autoflake

- .gitignore
- AUTHORS.rst
- MANIFEST.in
- Makefile
- autoflake.py
- test_acid.py
- test_acid_pypi.py
- test_autoflake.py
This will prevent a `from something import a, b, c`  to be splitted.
Test code 
```python
from math import sqrt, log, tan, cos
import os, sys, collections
print(log(2))
print(tan(5))
print(os)
print(sys)
```
Result
```diff
--- original/tes.py
+++ fixed/tes.py
@@ -1,5 +1,6 @@
-from math import sqrt, log, tan, cos
-import os, sys, collections
+from math import log, tan
+import os
+import sys
print(log(2))
print(tan(5))
```
Closes https://github.com/myint/autoflake/issues/7
> Prevent `from * import *` to be splitted

- README.rst
- autoflake.py
- test_autoflake.py
- test_fuzz.py
This patch add new feature to automatically expand a star 
(wildcard) import to specify all names that used inside the code.
A sample code like this
```python
from math import *
sin(1)
cos(0)
```
will be changed into 
```python
from math import cos, sin
sin(1)
cos(0)
```
Note that there are still 2 bugs regarding this feature, 
which mainly caused by related upstream bug from pyflakes:
1. A function/names that declared but later deleted by `del` 
command will raise a false positive that the names is
undeclared and could possibly come from a star import 
(if present).
https://github.com/PyCQA/pyflakes/issues/175
2. pyflakes is "inconsistent" on defining an undefined var 
in case of `__all__ `is used (like in module API files).
```python
from foo import * # contain function_1 and function_2 …
```
> Add option to expand single star import

- setup.py
``pyflakes.messages.ImportStarUsage`` only got introduced in v 1.1.0
Fixes https://github.com/myint/autoflake/issues/21
> Bump Pyflakes to 1.1.0

- autoflake.py
- test_autoflake.py
Add ``--exclude`` CLI option to ignore files/dir glob. Code taken from
https://github.com/hhatto/autopep8/blob/ce4c6333a7bc3a7a83ef4e65591082e67d82a180/autopep8.py#L3724
Closes https://github.com/myint/autoflake/issues/11
Hmm... because I take the code from there, I guess I will need a permission from you @myint? :smile:
> Add exclude parameter

- .travis.yml
- Makefile
- autoflake.py
- test_autoflake.py
This will automatically remove duplicate dictionary keys with the
`--remove-duplicate-keys` argument.
Closes https://github.com/myint/autoflake/issues/27
```diff
--- original/../test.py
+++ fixed/../test.py
@@ -1,15 +1,9 @@
print({
-  'b': 456,
-  'a': 123,
-  'b': 7834,
'a': 'wow',
-  'b': 456,
-  'c': 'hello',
'c': 'hello2',
-  'b': 'hiya',
'b': 'hiya',
})
-print({ 'a': 123, 'a': 567 })
-print({ 'b': 123, 'b': 567, 'b': 897, 'c': 'hello' })
-print({ 'a': 'first value', 'c': 123, 'd': 'hjfkds', 'c': 567, 'g': 'hi', 'c': 'this value will stay', 'd': 'so will this one' })
+print({ 'a': 567 })
+print({ 'b': 897, 'c': 'hello' })
+print({ 'a': 'first value', 'g': 'hi', 'c': 'this value will stay', 'd': 'so will this one' })
```
> Remove duplicate dictionary keys

- autoflake.py
Have `standard_paths` look in both platform-specific and platform-independent directories.  Fixes issue #32.
> standard_paths in plat_specific True and False

- README.rst
Add note about # noqa comments to disable autoflake in specific lines
> Add note about # noqa comments to disable autoflake in specific lines

- autoflake.py
- test_autoflake.py
When used, this new CLI argument will cause
autoflake to ignore unused imports when
checking any `__init__.py` files.
New tests have also been added to
accompany this new feature.
Closes https://github.com/myint/autoflake/issues/35
> autoflake.py: Add --ignore-init-module-imports

- autoflake.py
- test_autoflake.py
When use `--exclude` option and glob pattern (ex: `test/**.py`) , exclude option is not reflected. I think exclude option should be reflected when specify files as same as specify folder.
> reflected exclude option when use glob

- AUTHORS.rst
- README.rst
- autoflake.py
- test_autoflake.py
By specifying the `--check` argument, the program will exit with a code of 1. This is useful if using as part of a CI pipeline that should fail if changes are necessary.
> Add check argument

- autoflake.py
- test_autoflake.py
In check mode, we print "No issue detected" after checking a file, and if that file contains no errors. This leads to lines like:
No issues detected!No issues detected!No issues detected!
Add a \n to make this slightly better.
> Fix newline after printing "No issues detected" during check mode

- .pre-commit-hooks.yaml
> Add pre-commit hooks config file

- autoflake.py
Small change to add a new line before exiting when `--check` is used.
> Write newline before exit

- setup.py
I just tested autoflake by using python  3.6 and 3.7 and there were no problem to work.
Could you add the supported python versions?
> add supported python versions

- autoflake.py
- test_autoflake.py
Added `--quiet` option, so that when `check`ing lots of python files which are ok you don't get all those success messages printed. Other option could be to emit that no issues only with `--verbose`, but modifying existing things could break stuff
> Added --quiet option to suppress no issues

- autoflake.py
- test_autoflake.py
Whenever that's set, the full output is always going to get printed to
stdout.
This is mainly intended for integration with editors, but it's made in a
way that is compatible with previous setups.
This includes a flag for the file name, I'm using `--stdin-display-name`
which matches what flake8 uses.
Closes #12.
Closes #37.
> Add support for reading the file contents from stdin

- .pre-commit-config.yaml
- autoflake.py
- setup.py
- test_autoflake.py
- test_fuzz.py
- test_fuzz_pypi.py
Python 3.6 (and 2) are no longer supported, so we can require Python 3.7
and drop all the legacy stuff.
Closes #111.
> Drop old code

- autoflake.py
`lib2to3` is deprecated and might not be able to fully parse Python 3.10. Remove it in favor of `tokenize.detect_encoding`.
https://docs.python.org/3/library/2to3.html?module-lib2to3#module-lib2to3
> Remove lib2to3 usage

- README.md
- autoflake.py
- setup.py
- test_autoflake.py
Simple implementation for the currently missing functionality to load configuration from certain files:
to do:
> load config from pyproject.toml or setup.cfg

- autoflake.py
Closes #98.
Maybe helps with #100?
> Use the new sysconfig module instead of distutils

- .pre-commit-config.yaml
- setup.cfg
[`codespell --write-changes .`](https://pypi.org/project/codespell)
* `setup.cfg`: `kewords` --> `keywords` as discussed in #140
> pre-commit: Fix typos using codespell

- README.md
- autoflake.py
- test_autoflake.py
Changes in this PR:
- Add two flags to customize autoflake's behavior for pass statements:
- ignore-pass-statements: allows the user to opt out of the removal of useless pass statements if desired.
- ignore-pass-after-docstring: allows the user to keep pass statements after a docstring (see below for caveat).
- Add tests for new flags.
- Update README.
Caveat: since autoflake does not use an AST, deciding whether a pass statement follows a docstring is not really possible (at least not with a LOT of effort), so the approach is to keep pass statements right after a line ending with triple quotes. This is most probably in 99% of the cases a pass after a docstring.
This adds the possibility of keeping pass statements after docstrings which are not useless and is one of the requested features …
> Add option to keep pass statements

- autoflake.py
- test_autoflake.py
This small change unifies the output when running autoflake with --check. Previously one could not know which files passed the checks. Now the output to stdout is unified with the output when a file doesn't pass the check.
> Unified output to stdout when using --check

- README.md
- autoflake.py
- test_autoflake.py
refer to [149](https://github.com/PyCQA/autoflake/issues/149) issue
> add config-file option

- autoflake.py
- test_autoflake.py
This change adds a new flag which makes it possible to get the power of --check and its exit codes but also a diff output to stdout. This was requested in an issue and seems like a good addition. Added new keyword to keep backwards compatibility. #110
> Add --check-diff flag which combines check and diff

- README.md
- autoflake.py
> Bump 1.7.0

- autoflake.py
- test_autoflake.py
The idea is that options set with flags take precedence over options set in the configuration file (any configuration file).
> Update merge_configuration_file to prefer values from flags

- autoflake.py
- test_autoflake.py
Next up I'll work on adding some type annotations to these functions, but let's get things green first.
Closes #160.
> Properly consider options from config file and flags

- autoflake.py
- test_autoflake.py
This makes sure that we don't break multiprocessing. Also introduce a
test to prevent future regressions. I should have added that test ages
ago :)
Closes #163.
> Use regular dictionary instead of defaultdict

- autoflake.py
- test_autoflake.py
This was generating a list with the empty string, which caused it to match any import as a glob.
Closes #169.
> Fix default value for `--imports`

- autoflake.py
When running autoflake on win64 with more than 60 cores the following error is encountered
```
> autoflake -c -r .\src
Exception in thread Thread-1:
Traceback (most recent call last):
File "c:\python\lib\threading.py", line 932, in _bootstrap_inner
self.run()
File "c:\python\lib\threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "c:\python\lib\multiprocessing\pool.py", line 519, in _handle_workers
cls._wait_for_updates(current_sentinels, change_notifier)
File "c:\python\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
wait(sentinels, timeout=timeout)
File "c:\python\lib\multiprocessing\connection.py", line 879, in wait
ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
File "c:\python\lib\multiprocessing\connection.py", line 811, in …
```
> Fixed multiprocessing issue on win64 with more than 60 cores

- autoflake.py
- test_autoflake.py
Fixes #176 
* Updates `useless_pass_line_numbers` to ignore `pass` after a docstring when `--ignore-pass-after-docstring` is used, even if there are empty lines between the docstring and the pass.
Example where pass will be ignored by `--ignore-pass-after-docstring` when it was not previously:
```py
class MyException(Exception):
"""Example class
This is an example docstring for the class.
"""
pass
```
> fix: Ignore pass multiple lines after docstring with flag

- pyproject.toml
The latest pyflake version removed handling of python 2.x ``# type:`` comments. As the dependency was not upper limited in release of autoflake, none of the available release of autoflake handle's 2.X style typing. It would be very convenient to have a last release that support it in autoflake before allowing pyflake > 3.0 again.
> Add upper limit to pyflake's version <3.0 to support handling of python 2.x ``# type: `` comments

- autoflake.py
- test_autoflake.py
When removing unused imports or breaking up lines, keep the original order.
Users can use other linters/formatters to fix import order (e.g. isort or reorder-python-imports).
Closes #229.
> Don't sort imports

- autoflake.py
- test_autoflake.py
Fixes #193 
Adds support for a TOML-formatted configuration file when using the `--config` command line argument.
Currently, passing a TOML file into the `--config` argument results in this error:
```sh
autoflake --config ./path/to/pyproject.toml test_me.py
```
> Support .toml configuration format with --config flag

- autoflake.py
- test_autoflake.py
This introduced a breaking change (#251).
This reverts commit 780b44f036ab8715d1299b74b4fd3c7f04e8ed4f.
> Revert "Support .toml configuration format with --config flag (#249)"

- .github/workflows/main.yaml
- .pre-commit-config.yaml
- autoflake.py
- pyproject.toml
- test_autoflake.py
- test_fuzz.py
- test_fuzz_pypi.py
Validate with pyright on pre-commit (requires dropping pre-commit CI).
> Add type annotations and validate with pyright

- .pre-commit-config.yaml
- autoflake.py
- Move from black to ruff-format
- `pre-commit autoupdate`
> Update pre-commit config

- autoflake.py
- test_autoflake.py
Closes #283 
Add support for passing the .toml config file in the `--config` argument.
`autoflake --config=test.toml file.py`
> Add support for passing the .toml config in the arguments

- README.md
- autoflake.py
- test_autoflake.py
Autoflake can now ignore files with the `# autoflake: ignore` comment on top.
Closes #97
> Add support of ignore comment on the top of the file

- autoflake.py
This should fix an issue on Window where the `setup.cfg` can contain non-ascii characters, and Python is trying to use cp1252. This should be safe as utf-8 is compatible with cp1252.
It's possible I'll eat my words and some other platform breaks with this change, but let's try.
Closes #294.
> Always set encoding when reading `setup.cfg`
